NAPOSCA/pantryplus

.gitignore, build.gradle
For continuous integration testing of jasmine. We don't actually have any jasmine tests yet so I set karma to pass if it didn't find any tests.
=> Added karma

src/test/java/org/wecancodeit/pantryplus/Product.java, src/test/java/org/wecancodeit/pantryplus/ProductTest.java
Pull this so category can have products in it
=> made product class

src/main/java/org/wecancodeit/pantryplus/Category.java, src/test/java/org/wecancodeit/pantryplus/CategoryTest.java
Anything you want, check me out.
=> Category class

src/main/java/org/wecancodeit/pantryplus/LineItem.java, src/main/java/org/wecancodeit/pantryplus/Product.java, src/test/java/org/wecancodeit/pantryplus/LineItemTest.java
Added line item class with product and quantity
=> Line item class

src/main/resources/static/layout.css, src/main/resources/static/style.css, src/main/resources/templates/cart.html, src/main/resources/templates/index.html
This isn't set up for Thymeleaf or MVC, it's just a static view that can be changed later.
=> Created shopping view

src/main/java/org/wecancodeit/pantryplus/PantryController.java
=> Non restfull controller

src/main/java/org/wecancodeit/pantryplus/Cart.java, src/main/java/org/wecancodeit/pantryplus/CartRestController.java, src/main/java/org/wecancodeit/pantryplus/LineItem.java
Method names have been adjusted so they align with their function, and changed other methods functions to align with their names.
=> Adjusting methods

src/main/java/org/wecancodeit/pantryplus/controllers/PantryController.java, src/main/resources/templates/user-form.html
Box now correctly submits false value when unchecked and goes to shopping page instead of giving 400 error
=> infant checkbox fix on user form

src/main/java/org/wecancodeit/pantryplus/cart/Cart.java, src/main/java/org/wecancodeit/pantryplus/lineitem/CountedLineItem.java, src/test/java/org/wecancodeit/pantryplus/cart/CartJpaTest.java, src/test/java/org/wecancodeit/pantryplus/lineitem/CountedLineItemTest.java
Fixes #71 by adding checks to CountedLineItem so that it can't be made negative.
=> CountedLineItems can no longer be negative

src/main/resources/templates/user-form.html
=> Made some inputs of user form required so that there are no bad submits

src/main/java/org/wecancodeit/pantryplus/cart/Cart.java, src/main/java/org/wecancodeit/pantryplus/product/CouponProduct.java, src/test/java/org/wecancodeit/pantryplus/cart/CartJpaTest.java
=> Increasing quantity past limit doesn't throw server errors anymore

src/main/resources/templates/shopping.html
=> moved th:unless in shopping page to fix javascript error

src/main/resources/static/css/style.css, src/main/resources/templates/user-form.html
Things are starting to look better
=> radio and some wording fixed

src/main/java/org/wecancodeit/pantryplus/controllers/PantryController.java, src/main/java/org/wecancodeit/pantryplus/user/User.java, src/main/resources/static/css/layout.css, src/main/resources/templates/user-form.html, src/test/java/org/wecancodeit/pantryplus/cart/CartJpaTest.java, src/test/java/org/wecancodeit/pantryplus/user/UserJpaTest.java, src/test/java/org/wecancodeit/pantryplus/user/UserTest.java
User can now enter first and last name on form and have them be added to User class in repo
=> User name input

src/main/resources/static/css/style.css, src/main/resources/templates/shopping.html
Made the images unable to be dragged, words unhighlightable, and made the font sans-serif.
=> made non-draggable/highlightable

src/main/java/org/wecancodeit/pantryplus/controllers/PantryController.java, src/main/resources/static/js/shopping.js, src/main/resources/templates/cart.html, src/test/java/org/wecancodeit/pantryplus/controllers/PantryControllerMockMvcTest.java, src/test/java/org/wecancodeit/pantryplus/controllers/PantryControllerTest.java
=> Switches use post and delete requests to make dichotomous LineItem's

src/main/resources/templates/fragments/interfaces.html
=> Switches remember state now

src/main/java/org/wecancodeit/pantryplus/ProductPopulator.java, src/main/resources/templates/shopping.html
=> changed Coupon to Choice Items

src/main/resources/templates/shopping.html
Fixed that thing that I approved and then disapproved.
=> changed choice items to choice points in shopping coupon aside

src/main/java/org/wecancodeit/pantryplus/ThymeleafConfig.java, src/main/java/org/wecancodeit/pantryplus/cart/Cart.java, src/main/java/org/wecancodeit/pantryplus/controllers/EmailController.java, src/main/java/org/wecancodeit/pantryplus/user/User.java, src/main/resources/templates/email-failure.html, src/main/resources/templates/order.html, src/test/java/org/wecancodeit/pantryplus/cart/CartJpaTest.java
I haven't used any inline styling because it wasn't working at first and I don't want to present something tomorrow at demo day that's broken.
=> Thymeleaf emails have more info

src/main/resources/static/css/layout.css
=> mouse changes over category on hover

src/main/java/org/wecancodeit/pantryplus/controllers/EmailController.java
Recipient of emails is now the bsfppantryplus email instead of my own.
=> Changed recipient of emails back to the food pantry, again.

src/main/resources/templates/cart.html, src/main/resources/templates/user-form.html
=> New window

src/main/resources/templates/user-form.html
=> Changed link to about-us to start at the root directory rather than local directory

src/main/resources/application.properties
Fixes #127 
I'm watching the Conjuring so no PR description tonight.
=> Switched to using env vars in application.properties
